"""baseline — create all tables from model metadata

Revision ID: 20260630120000
Revises:
Create Date: 2026-06-30

ponytail: the initial migration creates the whole schema directly from
``Base.metadata`` rather than hand-enumerating every column, so it can never
drift from the models on day one. Subsequent migrations should be normal
autogenerated diffs (``make makemigrations m="..."``), which produce explicit
op.* statements against this baseline.
"""

from typing import Sequence, Union

from alembic import op

from src.db.base import Base
import src.models  # noqa — registers every model on Base.metadata

revision: str = "20260630120000"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
