"""baseline schema — the whole database, as explicit operations

Revision ID: 20260805164116
Revises:
Create Date: 2026-08-05

Squashes the four original revisions into one. The first of those built the
schema with ``Base.metadata.create_all()``, which meant it replayed whatever the
models looked like *today* — so on a fresh database it created tables the later
revisions then tried to create again, and ``alembic upgrade head`` died on
``DuplicateTable``. A migration must describe a fixed point in time, never the
current models: keep autogenerating explicit ``op.*`` diffs from here
(``make makemigrations m="..."``).

``tests/integration/test_migrations.py`` runs this chain on an empty database and
asserts autogenerate finds no remaining diff against the models.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Enum types are created implicitly by the sa.Enum columns below; autogenerate
# never emits the matching DROP TYPE, so downgrade has to name them itself or a
# re-upgrade fails with "type already exists".
_ENUMS = ("article_source_enum", "curation_item_type_enum", "curation_status_enum", "package_ecosystem_enum")

revision: str = '20260805164116'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mi__articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('devto', 'medium', 'rss', 'hackernews', name='article_source_enum'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('title_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mi__articles_dedup_key'), 'mi__articles', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_mi__articles_deleted_at'), 'mi__articles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_mi__articles_published_at'), 'mi__articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_mi__articles_source'), 'mi__articles', ['source'], unique=False)
    op.create_index(op.f('ix_mi__articles_title_fingerprint'), 'mi__articles', ['title_fingerprint'], unique=False)
    op.create_table('mi__curation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('repository', 'library_release', 'article', name='curation_item_type_enum'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('importance_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'failed', name='curation_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('raw_llm_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_type', 'item_id', name='uq_mi__curation__item')
    )
    op.create_index(op.f('ix_mi__curation_importance_score'), 'mi__curation', ['importance_score'], unique=False)
    op.create_index(op.f('ix_mi__curation_item_id'), 'mi__curation', ['item_id'], unique=False)
    op.create_index(op.f('ix_mi__curation_item_type'), 'mi__curation', ['item_type'], unique=False)
    op.create_index(op.f('ix_mi__curation_reviewed_at'), 'mi__curation', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_mi__curation_status'), 'mi__curation', ['status'], unique=False)
    op.create_table('mi__libraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('ecosystem', sa.Enum('pypi', 'npm', name='package_ecosystem_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_version', sa.String(length=64), nullable=True),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mi__libraries_dedup_key'), 'mi__libraries', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_mi__libraries_deleted_at'), 'mi__libraries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_mi__libraries_is_monitored'), 'mi__libraries', ['is_monitored'], unique=False)
    op.create_table('mi__preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stacks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('monitored_libraries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mi__repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('stars_per_week', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repo_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mi__repositories_collected_at'), 'mi__repositories', ['collected_at'], unique=False)
    op.create_index(op.f('ix_mi__repositories_dedup_key'), 'mi__repositories', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_mi__repositories_deleted_at'), 'mi__repositories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_mi__repositories_relevance_score'), 'mi__repositories', ['relevance_score'], unique=False)
    op.create_table('mi__task_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mi__task_runs_finished_at'), 'mi__task_runs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_mi__task_runs_task_name'), 'mi__task_runs', ['task_name'], unique=False)
    op.create_table('mi__library_releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('previous_version', sa.String(length=64), nullable=True),
    sa.Column('new_version', sa.String(length=64), nullable=False),
    sa.Column('is_major', sa.Boolean(), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['mi__libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mi__library_releases_dedup_key'), 'mi__library_releases', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_mi__library_releases_is_major'), 'mi__library_releases', ['is_major'], unique=False)
    op.create_index(op.f('ix_mi__library_releases_library_id'), 'mi__library_releases', ['library_id'], unique=False)
    op.create_table('mi__repository_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('stars_per_week', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['mi__repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mi__repository_snapshots_repository_id'), 'mi__repository_snapshots', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mi__repository_snapshots_repository_id'), table_name='mi__repository_snapshots')
    op.drop_table('mi__repository_snapshots')
    op.drop_index(op.f('ix_mi__library_releases_library_id'), table_name='mi__library_releases')
    op.drop_index(op.f('ix_mi__library_releases_is_major'), table_name='mi__library_releases')
    op.drop_index(op.f('ix_mi__library_releases_dedup_key'), table_name='mi__library_releases')
    op.drop_table('mi__library_releases')
    op.drop_index(op.f('ix_mi__task_runs_task_name'), table_name='mi__task_runs')
    op.drop_index(op.f('ix_mi__task_runs_finished_at'), table_name='mi__task_runs')
    op.drop_table('mi__task_runs')
    op.drop_index(op.f('ix_mi__repositories_relevance_score'), table_name='mi__repositories')
    op.drop_index(op.f('ix_mi__repositories_deleted_at'), table_name='mi__repositories')
    op.drop_index(op.f('ix_mi__repositories_dedup_key'), table_name='mi__repositories')
    op.drop_index(op.f('ix_mi__repositories_collected_at'), table_name='mi__repositories')
    op.drop_table('mi__repositories')
    op.drop_table('mi__preferences')
    op.drop_index(op.f('ix_mi__libraries_is_monitored'), table_name='mi__libraries')
    op.drop_index(op.f('ix_mi__libraries_deleted_at'), table_name='mi__libraries')
    op.drop_index(op.f('ix_mi__libraries_dedup_key'), table_name='mi__libraries')
    op.drop_table('mi__libraries')
    op.drop_index(op.f('ix_mi__curation_status'), table_name='mi__curation')
    op.drop_index(op.f('ix_mi__curation_reviewed_at'), table_name='mi__curation')
    op.drop_index(op.f('ix_mi__curation_item_type'), table_name='mi__curation')
    op.drop_index(op.f('ix_mi__curation_item_id'), table_name='mi__curation')
    op.drop_index(op.f('ix_mi__curation_importance_score'), table_name='mi__curation')
    op.drop_table('mi__curation')
    op.drop_index(op.f('ix_mi__articles_title_fingerprint'), table_name='mi__articles')
    op.drop_index(op.f('ix_mi__articles_source'), table_name='mi__articles')
    op.drop_index(op.f('ix_mi__articles_published_at'), table_name='mi__articles')
    op.drop_index(op.f('ix_mi__articles_deleted_at'), table_name='mi__articles')
    op.drop_index(op.f('ix_mi__articles_dedup_key'), table_name='mi__articles')
    op.drop_table('mi__articles')
    # ### end Alembic commands ###
    for enum_name in _ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
